<template>
  <div class="pit-page">
    <section class="card workflow-card">
      <div class="card-header"><div><strong>个税核对底稿</strong><p>当前公司和所属期间只有一份数据库底稿，重算会更新自动结果并保留仍存在记录的人工原因。</p></div><span class="tag" :class="overview?.workpaper?.data_status === 'ready' ? 'tag-success' : 'tag-warning'">{{ overview?.exists ? stageLabel : '未生成' }}</span></div>
      <div class="card-body pit-toolbar"><div><small>上次计算</small><strong>{{ overview?.workpaper?.last_calculated_at || '—' }}</strong></div><el-button type="primary" :loading="calculating" :disabled="!periodId" @click="recalculate"><el-icon><RefreshRight /></el-icon>{{ overview?.exists ? '重新计算' : '生成本月底稿' }}</el-button></div>
    </section>
    <section class="card workflow-card"><div class="card-header"><strong>数据源状态</strong><el-button link @click="load">刷新</el-button></div><div class="card-body source-grid"><div v-for="source in readiness" :key="source.source_type" class="source-item"><span>{{ sourceLabel(source.source_type) }}</span><strong :class="`source-${source.source_status}`">{{ source.source_status }}</strong><small>{{ source.row_count }} 行</small></div></div></section>
    <section v-if="overview?.exists" class="card workflow-card"><div class="card-body"><el-tabs v-model="tab"><el-tab-pane label="机构汇总" name="summary"><el-table :data="summaries" size="small" max-height="460"><el-table-column prop="org_code" label="机构" width="100"/><el-table-column prop="org_name" label="营业部" min-width="130"/><el-table-column label="申报税额" width="110"><template #default="{row}">{{ money(row.declared_tax_amount) }}</template></el-table-column><el-table-column label="差异1" width="105"><template #default="{row}"><span :class="differenceClass(row.difference_1)">{{ money(row.difference_1) }}</span></template></el-table-column><el-table-column label="差异2" width="105"><template #default="{row}"><span :class="differenceClass(row.difference_2)">{{ money(row.difference_2) }}</span></template></el-table-column><el-table-column label="差异3" width="105"><template #default="{row}">{{ money(row.taxable_income_difference) }}</template></el-table-column><el-table-column label="人工原因" min-width="180"><template #default="{row}"><el-input :model-value="row.difference_1_manual_reason" size="small" placeholder="—" @change="patch('summary', row, $event)"/></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="税额科目" name="tax"><el-table :data="taxChecks" size="small" max-height="460"><el-table-column prop="org_code" label="机构" width="100"/><el-table-column prop="subject_code" label="科目" width="105"/><el-table-column label="业务税额" width="110"><template #default="{row}">{{ money(row.business_tax_amount) }}</template></el-table-column><el-table-column label="申报税额" width="110"><template #default="{row}">{{ money(row.declared_tax_amount) }}</template></el-table-column><el-table-column label="业务申报差异" width="125"><template #default="{row}"><span :class="differenceClass(row.business_declared_difference)">{{ money(row.business_declared_difference) }}</span></template></el-table-column><el-table-column prop="check_status" label="状态" width="115"/></el-table></el-tab-pane>
      <el-tab-pane label="发生额" name="occurrence"><el-table :data="occurrenceChecks" size="small" max-height="460"><el-table-column prop="org_code" label="机构" width="100"/><el-table-column prop="subject_code" label="科目" width="105"/><el-table-column prop="income_type" label="所得项目" min-width="150"/><el-table-column label="发生额" width="110"><template #default="{row}">{{ money(row.occurrence_amount) }}</template></el-table-column><el-table-column label="申报差异" width="115"><template #default="{row}">{{ money(row.declared_income_difference) }}</template></el-table-column><el-table-column prop="check_status" label="状态" width="115"/></el-table></el-tab-pane>
      <el-tab-pane label="申报汇总" name="declarations"><el-table :data="declarationSummaries" size="small" max-height="460"><el-table-column prop="org_code" label="机构" width="100"/><el-table-column prop="declaration_type" label="申报类型" min-width="150"/><el-table-column prop="income_item" label="所得项目" min-width="200"/><el-table-column label="收入" width="120"><template #default="{row}">{{ money(row.income_amount) }}</template></el-table-column><el-table-column label="税额" width="120"><template #default="{row}">{{ money(row.tax_amount) }}</template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="人员/客户差异" name="details"><el-table :data="details" size="small" max-height="460"><el-table-column prop="detail_type" label="类型" width="150"/><el-table-column prop="org_code" label="机构" width="95"/><el-table-column prop="person_or_customer_name" label="人员/客户" min-width="130"/><el-table-column label="业务金额" width="110"><template #default="{row}">{{ money(row.source_amount) }}</template></el-table-column><el-table-column label="申报金额" width="110"><template #default="{row}">{{ money(row.target_amount) }}</template></el-table-column><el-table-column label="差异" width="100"><template #default="{row}"><span :class="differenceClass(row.difference)">{{ money(row.difference) }}</span></template></el-table-column><el-table-column label="自动原因" min-width="220"><template #default="{row}">{{ row.auto_reason || '—' }}</template></el-table-column><el-table-column label="人工原因" min-width="180"><template #default="{row}"><el-input :model-value="row.manual_reason" size="small" placeholder="填写原因" @change="patch('detail', row, $event)"/></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="完税/银行" name="bank"><el-table :data="bankMatches" size="small" max-height="460"><el-table-column prop="org_code" label="机构" width="100"/><el-table-column prop="bank_account" label="银行账号" min-width="160"/><el-table-column prop="transaction_time" label="交易时间" width="160"/><el-table-column prop="transaction_summary" label="摘要" min-width="180"/><el-table-column label="匹配金额" width="120"><template #default="{row}">{{ money(row.debit_amount) }}</template></el-table-column></el-table></el-tab-pane></el-tabs></div></section>
  </div>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { RefreshRight } from '@element-plus/icons-vue'
import { pitReconciliationApi } from '../api'
const props = defineProps<{ periodId: number | null }>()
const overview = ref<any>(null); const readiness = ref<any[]>([]); const summaries = ref<any[]>([]); const taxChecks=ref<any[]>([]); const occurrenceChecks=ref<any[]>([]); const declarationSummaries=ref<any[]>([]); const details=ref<any[]>([]); const bankMatches=ref<any[]>([]); const calculating=ref(false); const tab=ref('summary')
const stageLabel=computed(()=>overview.value?.workpaper?.stage === 'post_payment' ? '缴款后核对' : '缴款前核对')
watch(()=>props.periodId,load,{immediate:true})
async function load(){ if(!props.periodId)return; try { const [o,r,s,t,c,d,ds,b]=await Promise.all([pitReconciliationApi.overview(props.periodId),pitReconciliationApi.readiness(props.periodId),pitReconciliationApi.summaries(props.periodId),pitReconciliationApi.taxChecks(props.periodId),pitReconciliationApi.occurrenceChecks(props.periodId),pitReconciliationApi.declarationSummaries(props.periodId),pitReconciliationApi.details(props.periodId),pitReconciliationApi.bankMatches(props.periodId)]); overview.value=o.data; readiness.value=r.data; summaries.value=s.data; taxChecks.value=t.data; occurrenceChecks.value=c.data; declarationSummaries.value=d.data; details.value=ds.data; bankMatches.value=b.data } catch(error:any){ if(error?.response?.status!==404) ElMessage.error(error?.response?.data?.detail || '底稿读取失败') } }
async function recalculate(){if(!props.periodId)return;calculating.value=true;try{await pitReconciliationApi.recalculate(props.periodId);ElMessage.success('底稿计算完成');await load()}catch(error:any){ElMessage.error(error?.response?.data?.detail||'计算失败')}finally{calculating.value=false}}
async function patch(kind:string,row:any,value:string){try{await pitReconciliationApi.patch(kind,row.id,{manual_reason:value});row.manual_reason=value;row.difference_1_manual_reason=value;ElMessage.success('人工原因已保存')}catch(error:any){ElMessage.error(error?.response?.data?.detail||'保存失败')}}
function money(value:any){return value===null||value===undefined?'—':Number(value).toFixed(2)} function differenceClass(value:any){return value!==null&&value!==undefined&&Math.abs(Number(value))>0.01?'difference':''} function sourceLabel(value:string){return ({organization_mapping:'机构映射',salary:'工资产物',pit_declaration:'个税申报',balance_sheet:'科目余额表',broker:'经纪人',bond_interest:'债券利息',restricted_stock:'限售股',tax_certificate:'完税证明',bank_statement:'银行流水'} as any)[value]||value}
</script>
<style scoped>
.pit-page{display:grid;gap:14px}.pit-toolbar{display:flex;justify-content:space-between;align-items:center}.pit-toolbar div{display:grid;gap:4px}.pit-toolbar small{color:#667085}.source-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px}.source-item{border:1px solid #e4e7ec;padding:10px;display:grid;gap:4px;border-radius:4px}.source-item small{color:#667085}.source-ready{color:#067647}.source-ready_empty{color:#475467}.source-missing,.source-invalid{color:#b42318}.difference{color:#b42318;font-weight:600}@media(max-width:700px){.pit-toolbar{align-items:flex-start;gap:12px;flex-direction:column}}
</style>
