<template>
  <div v-loading="pageLoading" class="pit-page">
    <section class="card workflow-card">
      <div class="card-header"><div><strong>个税核对底稿</strong><p>同公司、同所属期唯一底稿；重新计算覆盖自动结果，并保留仍存在记录的人工原因。</p></div><span class="tag" :class="overview?.workpaper?.data_status === 'ready' ? 'tag-success' : 'tag-warning'">{{ overview?.exists ? stageLabel : '未生成' }}</span></div>
      <div class="card-body pit-toolbar"><div><small>上次计算</small><strong>{{ overview?.workpaper?.last_calculated_at || '—' }}</strong></div><el-button type="primary" :loading="recalculateLoading" :disabled="!periodId" @click="recalculate"><el-icon><RefreshRight /></el-icon>{{ overview?.exists ? '重新计算' : '生成本月底稿' }}</el-button></div>
    </section>

    <section class="card workflow-card pit-source-panel">
      <div class="card-header"><strong>数据准备情况</strong><el-button link @click="loadReadiness">刷新</el-button></div>
      <div class="card-body pit-source-grid"><div v-for="source in readiness" :key="source.source_type" class="pit-source-card"><div class="source-name">{{ sourceLabels[source.source_type] ?? source.source_type }}</div><strong :class="`source-${source.source_status}`">{{ sourceStatusLabels[source.source_status] ?? source.source_status }}</strong><small v-if="source.row_count !== null">{{ source.row_count }} 条</small><small v-if="source.source_ref" class="source-ref">来源：{{ source.source_ref }}</small><el-tooltip v-if="source.issues_json?.length" :content="source.issues_json[0]?.message || '数据存在异常'"><span class="source-issue">查看异常</span></el-tooltip></div></div>
    </section>

    <section v-if="overview?.exists" class="card workflow-card">
      <div class="card-body pit-filter-bar"><el-select v-model="orgFilter" clearable filterable placeholder="全部机构" class="pit-filter-org"><el-option v-for="item in organizationOptions" :key="item" :label="item" :value="item" /></el-select><el-input v-model="keyword" clearable placeholder="搜索机构、姓名、客户或科目" class="pit-filter-keyword" /><el-radio-group v-model="displayMode"><el-radio-button label="all">全部</el-radio-button><el-radio-button label="difference">仅差异</el-radio-button><el-radio-button label="missing">仅缺失</el-radio-button></el-radio-group></div>
      <div class="card-body">
        <el-tabs v-model="activeTab" @tab-change="handleTabChange">
          <el-tab-pane label="机构汇总" name="summary">
            <div class="pit-table-wrap"><el-table v-loading="tabLoading.summary" :data="filteredSummaryRows" border stripe max-height="500" class="pit-reconciliation-table"><el-table-column prop="org_code" label="机构代码" width="105" fixed="left" /><el-table-column prop="org_name" label="营业部" width="180" fixed="left" />
              <el-table-column label="账务税额核对"><MoneyColumn label="申报税额" field="declared_tax_amount" /><MoneyColumn label="账面余额" field="balance_tax_amount" /><SummaryDifferenceColumn label="差异1" field="difference_1" tab="taxAmount" /><ReasonColumn field="difference_1_manual_reason" kind="summary" /></el-table-column>
              <el-table-column label="工资/业务税额核对"><MoneyColumn label="范围申报税额" field="scoped_declared_tax_amount" /><MoneyColumn label="工资/业务税额" field="payroll_business_tax_amount" /><SummaryDifferenceColumn label="差异2" field="difference_2" tab="taxAmount" /><ReasonColumn field="difference_2_manual_reason" kind="summary" /></el-table-column>
              <el-table-column label="累计应纳税所得额核对"><SummaryDifferenceColumn label="差异3" field="taxable_income_difference" tab="salaryTaxableIncome" /><ReasonColumn field="difference_3_manual_reason" kind="summary" /></el-table-column>
              <el-table-column label="申报/完税"><MoneyColumn label="完税金额" field="certificate_tax_amount" /><SummaryDifferenceColumn label="差异4" field="difference_4" tab="payment" /><ReasonColumn field="difference_4_manual_reason" kind="summary" /></el-table-column>
              <el-table-column label="完税/银行"><MoneyColumn label="银行金额" field="bank_tax_amount" /><SummaryDifferenceColumn label="差异5" field="difference_5" tab="payment" /><ReasonColumn field="difference_5_manual_reason" kind="summary" /></el-table-column>
              <el-table-column label="经纪人发生额"><SummaryDifferenceColumn label="差异6" field="broker_occurrence_difference" tab="occurrence" /><ReasonColumn field="difference_6_manual_reason" kind="summary" /></el-table-column>
              <el-table-column label="其他收入"><SummaryDifferenceColumn label="差异7" field="other_income_difference" tab="occurrence" /><ReasonColumn field="difference_7_manual_reason" kind="summary" /></el-table-column><el-table-column prop="check_status" label="状态" width="105" fixed="right" />
            </el-table></div>
          </el-tab-pane>
          <el-tab-pane label="个税明细税额" name="taxAmount">
            <div class="pit-table-wrap"><el-table v-loading="tabLoading.taxAmount" :data="filteredTaxRows" border stripe max-height="500" class="pit-reconciliation-table"><el-table-column prop="org_code" label="机构" width="100" fixed="left" /><el-table-column prop="org_name" label="营业部" width="150" fixed="left" /><el-table-column prop="subject_code" label="科目" width="105" /><el-table-column prop="subject_name" label="科目名称" width="170" />
              <el-table-column label="账务数据"><MoneyColumn v-for="column in balanceColumns" :key="column.key" :label="column.label" :field="column.key" /></el-table-column>
              <el-table-column label="本期账务核对"><MoneyColumn label="申报税额" field="declared_tax_amount" /><DifferenceColumn label="本期差异" field="current_difference" /><ReasonColumn field="current_manual_reason" kind="tax" /></el-table-column>
              <el-table-column label="累计账务核对"><DifferenceColumn label="累计差异" field="cumulative_difference" /><ReasonColumn field="cumulative_manual_reason" kind="tax" /></el-table-column>
              <el-table-column label="工资/业务核对"><MoneyColumn label="范围申报税额" field="scoped_declared_tax_amount" /><MoneyColumn label="工资/业务税额" field="business_tax_amount" /><TaxDifferenceColumn /><ReasonColumn field="business_declared_manual_reason" kind="tax" /></el-table-column><el-table-column prop="check_status" label="状态" width="105" fixed="right" />
            </el-table></div>
          </el-tab-pane>
          <el-tab-pane label="其他个税发生额" name="occurrence">
            <div class="pit-table-wrap"><el-table v-loading="tabLoading.occurrence" :data="filteredOccurrenceRows" border stripe max-height="500" class="pit-reconciliation-table"><el-table-column prop="org_code" label="机构" width="100" fixed="left" /><el-table-column prop="org_name" label="营业部" width="150" fixed="left" /><el-table-column prop="subject_code" label="科目" width="105" /><el-table-column prop="subject_name" label="科目名称" width="160" /><el-table-column prop="income_type" label="所得项目" width="180" />
              <el-table-column label="账务数据"><MoneyColumn v-for="column in occurrenceBalanceColumns" :key="column.key" :label="column.label" :field="column.key" /></el-table-column>
              <el-table-column label="经纪人发生额"><MoneyColumn label="工资金额" field="broker_payroll_amount" /><DifferenceColumn label="差异" field="broker_occurrence_difference" /><ReasonColumn field="broker_occurrence_manual_reason" kind="occurrence" /></el-table-column>
              <el-table-column label="申报收入"><MoneyColumn label="应申报收入" field="expected_declared_income" /><MoneyColumn label="实际申报收入" field="actual_declared_income" /><DifferenceColumn label="差异" field="declared_income_difference" /><ReasonColumn field="declared_income_manual_reason" kind="occurrence" /></el-table-column><el-table-column prop="expected_income_description" label="计算说明" width="200" show-overflow-tooltip /><el-table-column prop="check_status" label="状态" width="105" fixed="right" />
            </el-table></div>
          </el-tab-pane>
          <el-tab-pane label="实际申报汇总" name="declaration"><div class="pit-table-wrap"><el-table v-loading="tabLoading.declaration" :data="filteredDeclarationRows" border stripe max-height="500"><el-table-column prop="org_code" label="机构" width="105" fixed="left" /><el-table-column prop="org_name" label="营业部" width="160" /><el-table-column prop="declaration_type" label="申报类型" width="150" /><el-table-column prop="income_item" label="所得项目" min-width="240" /><el-table-column prop="person_count" label="人数" width="80" align="right" /><MoneyColumn label="收入" field="income_amount" /><MoneyColumn label="税额" field="tax_amount" /></el-table></div></el-tab-pane>
          <el-tab-pane label="工资薪金税额差异" name="salaryTax"><div class="pit-table-wrap"><el-table v-loading="tabLoading.salaryTax" :data="filteredSalaryTaxRows" border stripe max-height="500"><el-table-column prop="org_code" label="机构" width="100" fixed="left" /><el-table-column prop="person_or_customer_name" label="姓名" width="130" /><el-table-column prop="id_number" label="证件号码" width="180" /><DetailMoneyColumn label="工资税额" :keys="['payroll_tax_amount']" fallback="source_amount" /><DetailMoneyColumn label="申报税额" :keys="['declared_tax_amount']" fallback="target_amount" /><DetailDifferenceColumn label="差异" /><el-table-column prop="auto_reason" label="自动分析" min-width="260" show-overflow-tooltip /><el-table-column label="人工原因" width="150"><template #default="{ row }"><ReasonButton :row="row" field="manual_reason" kind="difference" /></template></el-table-column><el-table-column label="核对项目" width="110"><template #default="{ row }"><el-button link type="primary" @click="openSalaryDrawer(row)">查看项目</el-button></template></el-table-column></el-table></div></el-tab-pane>
          <el-tab-pane label="累计应纳税所得额差异" name="salaryTaxableIncome"><div class="pit-table-wrap"><el-table v-loading="tabLoading.salaryTaxableIncome" :data="filteredSalaryTaxableIncomeRows" border stripe max-height="500"><el-table-column prop="org_code" label="机构" width="100" fixed="left" /><el-table-column prop="person_or_customer_name" label="姓名" width="120" /><el-table-column prop="id_number" label="证件号码" width="170" /><DetailMoneyColumn label="工资累计所得额" :keys="['payroll_taxable_income', 'payroll_cumulative_taxable_income']" /><DetailMoneyColumn label="申报累计所得额" :keys="['declared_taxable_income']" /><DetailDifferenceColumn label="所得额差异" /><DetailMoneyColumn label="专项扣除差异" :keys="['specific_deduction_difference']" /><DetailMoneyColumn label="专项附加差异" :keys="['special_additional_deduction_difference']" /><DetailMoneyColumn label="其他扣除差异" :keys="['other_deduction_difference', 'other_difference']" /><el-table-column label="税率" width="80"><template #default="{ row }">{{ detailValue(row, 'declaration_rate') ?? '—' }}</template></el-table-column><DetailMoneyColumn label="工资税" :keys="['payroll_tax']" /><DetailMoneyColumn label="申报税" :keys="['declared_tax']" /><DetailMoneyColumn label="税额差异" :keys="['tax_difference']" /><el-table-column label="人工原因" width="150"><template #default="{ row }"><ReasonButton :row="row" field="manual_reason" kind="difference" /></template></el-table-column></el-table></div></el-tab-pane>
          <el-tab-pane label="客户利息个税差异" name="bondInterest"><div class="pit-table-wrap"><el-table v-loading="tabLoading.bondInterest" :data="filteredBondInterestRows" border stripe max-height="500"><el-table-column prop="org_code" label="机构" width="100" fixed="left" /><el-table-column prop="person_or_customer_name" label="客户" width="130" /><el-table-column prop="id_number" label="证件号码" width="180" /><DetailMoneyColumn label="债券兑息" :keys="['interest_amount']" /><DetailMoneyColumn label="业务兑息扣税" :keys="['business_tax_amount']" fallback="source_amount" /><DetailMoneyColumn label="申报税额" :keys="['declared_tax_amount']" fallback="target_amount" /><DetailDifferenceColumn label="差异" /><el-table-column label="同名客户" width="100"><template #default="{ row }">{{ row.detail_json?.same_name_merged ? '是' : '否' }}</template></el-table-column><el-table-column prop="auto_reason" label="自动原因" min-width="240" show-overflow-tooltip /><el-table-column label="人工原因" width="150"><template #default="{ row }"><ReasonButton :row="row" field="manual_reason" kind="difference" /></template></el-table-column></el-table></div></el-tab-pane>
          <el-tab-pane label="限售股个税差异" name="restrictedStock"><div class="pit-table-wrap"><el-table v-loading="tabLoading.restrictedStock" :data="filteredRestrictedStockRows" border stripe max-height="500"><el-table-column prop="org_code" label="机构" width="100" fixed="left" /><el-table-column prop="person_or_customer_name" label="客户" width="130" /><el-table-column prop="id_number" label="证件号码" width="180" /><el-table-column label="证券名称" width="180"><template #default="{ row }">{{ detailList(row, 'security_names') || '—' }}</template></el-table-column><DetailMoneyColumn label="卖出金额" :keys="['sale_amount']" /><DetailMoneyColumn label="业务税额" :keys="['business_tax_amount']" fallback="source_amount" /><DetailMoneyColumn label="申报扣缴税额" :keys="['declared_tax_amount']" fallback="target_amount" /><DetailDifferenceColumn label="差异" /><el-table-column label="人工原因" width="150"><template #default="{ row }"><ReasonButton :row="row" field="manual_reason" kind="difference" /></template></el-table-column></el-table></div></el-tab-pane>
          <el-tab-pane label="完税及银行核对" name="payment"><div class="pit-table-wrap"><el-table v-loading="tabLoading.payment" :data="filteredSummaryRows" border stripe max-height="280" @row-click="selectPaymentOrg"><el-table-column prop="org_code" label="机构" width="105" fixed="left" /><el-table-column prop="org_name" label="营业部" width="160" /><MoneyColumn label="申报税额" field="declared_tax_amount" /><MoneyColumn label="完税金额" field="certificate_tax_amount" /><DifferenceColumn label="差异4" field="difference_4" /><ReasonColumn field="difference_4_manual_reason" kind="summary" /><MoneyColumn label="银行金额" field="bank_tax_amount" /><DifferenceColumn label="差异5" field="difference_5" /><ReasonColumn field="difference_5_manual_reason" kind="summary" /></el-table></div><div class="pit-subtitle">银行匹配明细{{ selectedPaymentOrgCode ? `：${selectedPaymentOrgCode}` : '' }}</div><div class="pit-table-wrap"><el-table :data="filteredBankMatches" border stripe max-height="320"><el-table-column prop="org_code" label="机构" width="105" /><el-table-column prop="org_full_name" label="营业部全称" min-width="180" /><el-table-column prop="bank_account" label="本方账号" width="170" /><el-table-column prop="transaction_time" label="交易时间" width="170" /><el-table-column prop="transaction_summary" label="交易摘要" min-width="220" /><MoneyColumn label="借方金额" field="debit_amount" /></el-table></div></el-tab-pane>
        </el-tabs>
      </div>
    </section>
    <el-dialog v-model="reasonDialogVisible" title="编辑差异原因" width="520px"><el-input v-model="editingReasonText" type="textarea" :rows="5" /><template #footer><el-button @click="reasonDialogVisible = false">取消</el-button><el-button type="primary" :loading="reasonSaving" @click="saveReason">保存</el-button></template></el-dialog>
    <el-drawer v-model="detailDrawerVisible" title="工资薪金核对项目" size="560px"><el-table :data="salaryComparisonItems" border size="small"><el-table-column prop="name" label="项目" min-width="150" /><el-table-column label="工资金额" width="110"><template #default="{ row }">{{ formatMoney(row.payroll_amount) }}</template></el-table-column><el-table-column label="申报金额" width="110"><template #default="{ row }">{{ formatMoney(row.declaration_amount) }}</template></el-table-column><el-table-column label="差异" width="105"><template #default="{ row }">{{ formatMoney(row.difference) }}</template></el-table-column><el-table-column prop="tax_rate" label="税率" width="75" /><el-table-column label="税额影响" width="105"><template #default="{ row }">{{ formatMoney(row.tax_effect) }}</template></el-table-column></el-table><div v-if="!salaryComparisonItems.length" class="empty-inline">该记录没有可展开的扣除项目。</div></el-drawer>
  </div>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, reactive, ref, watch } from 'vue'
import { ElButton, ElMessage, ElTableColumn } from 'element-plus'
import { RefreshRight } from '@element-plus/icons-vue'
import { pitReconciliationApi, type PitBankTaxMatch, type PitDeclarationSummary, type PitDifferenceDetail, type PitOccurrenceCheck, type PitOrgSummary, type PitOverviewResponse, type PitReadinessItem, type PitTaxAmountCheck } from '../api'

type PitTabKey = 'summary' | 'taxAmount' | 'occurrence' | 'declaration' | 'salaryTax' | 'salaryTaxableIncome' | 'bondInterest' | 'restrictedStock' | 'payment'
type ReasonKind = 'summary' | 'tax' | 'occurrence' | 'difference'
type ReasonField = 'difference_1_manual_reason' | 'difference_2_manual_reason' | 'difference_3_manual_reason' | 'difference_4_manual_reason' | 'difference_5_manual_reason' | 'difference_6_manual_reason' | 'difference_7_manual_reason' | 'current_manual_reason' | 'cumulative_manual_reason' | 'business_declared_manual_reason' | 'broker_occurrence_manual_reason' | 'declared_income_manual_reason' | 'manual_reason'
type TableRow = Record<string, unknown>
const props = defineProps<{ periodId: number | null }>()
const overview = ref<PitOverviewResponse | null>(null); const readiness = ref<PitReadinessItem[]>([]); const summaryRows = ref<PitOrgSummary[]>([]); const taxAmountRows = ref<PitTaxAmountCheck[]>([]); const occurrenceRows = ref<PitOccurrenceCheck[]>([]); const declarationRows = ref<PitDeclarationSummary[]>([]); const salaryTaxRows = ref<PitDifferenceDetail[]>([]); const salaryTaxableIncomeRows = ref<PitDifferenceDetail[]>([]); const bondInterestRows = ref<PitDifferenceDetail[]>([]); const restrictedStockRows = ref<PitDifferenceDetail[]>([]); const bankMatchRows = ref<PitBankTaxMatch[]>([])
const activeTab = ref<PitTabKey>('summary'); const pageLoading = ref(false); const recalculateLoading = ref(false); const orgFilter = ref(''); const keyword = ref(''); const displayMode = ref<'all' | 'difference' | 'missing'>('all'); const selectedPaymentOrgCode = ref<string | null>(null)
const tabLoading = reactive<Record<PitTabKey, boolean>>({ summary:false,taxAmount:false,occurrence:false,declaration:false,salaryTax:false,salaryTaxableIncome:false,bondInterest:false,restrictedStock:false,payment:false }); const tabLoaded = reactive<Record<PitTabKey, boolean>>({ summary:false,taxAmount:false,occurrence:false,declaration:false,salaryTax:false,salaryTaxableIncome:false,bondInterest:false,restrictedStock:false,payment:false })
const reasonDialogVisible = ref(false); const reasonSaving = ref(false); const editingReasonRow = ref<TableRow | null>(null); const editingReasonField = ref<ReasonField | null>(null); const editingReasonKind = ref<ReasonKind>('summary'); const editingReasonText = ref(''); const detailDrawerVisible = ref(false); const detailDrawerRow = ref<PitDifferenceDetail | null>(null)
const sourceLabels: Record<string, string> = { organization_mapping:'机构主数据', salary:'工资薪金', pit_declaration:'实际个税申报', balance_sheet:'科目余额表', broker:'证券经纪人', bond_interest:'债券利息', restricted_stock:'限售股', tax_certificate:'完税证明', bank_statement:'银行流水' }; const sourceStatusLabels: Record<string, string> = { ready:'已就绪', ready_empty:'已就绪（无记录）', missing:'缺失', invalid:'数据异常', not_applicable:'无相关业务' }
const balanceColumns = [{ key:'opening_balance',label:'期初' },{ key:'debit_amount',label:'借方' },{ key:'credit_amount',label:'贷方' },{ key:'closing_balance',label:'期末' }]; const occurrenceBalanceColumns = [...balanceColumns,{ key:'occurrence_amount',label:'发生额' }]
const stageLabel = computed(() => overview.value?.workpaper?.stage === 'post_payment' ? '缴款后核对' : '缴款前核对'); const organizationOptions = computed(() => [...new Set(summaryRows.value.map((row) => row.org_code).filter(Boolean))]); const salaryComparisonItems = computed(() => Array.isArray(detailDrawerRow.value?.detail_json?.comparison_items) ? detailDrawerRow.value?.detail_json?.comparison_items as TableRow[] : [])
function formatMoney(value: unknown): string { if (value === null || value === undefined || value === '') return '—'; const numeric = Number(value); return Number.isFinite(numeric) ? numeric.toLocaleString('zh-CN',{ minimumFractionDigits:2,maximumFractionDigits:2 }) : '—' }
function isDifference(value: unknown): boolean { return value !== null && value !== undefined && value !== '' && Number.isFinite(Number(value)) && Math.abs(Number(value)) > .01 }
function differenceClass(value: unknown) { return `pit-diff pit-diff--${value === null || value === undefined || value === '' ? 'missing' : isDifference(value) ? 'difference' : 'ok'}` }
function detailValue(row: { detail_json?: Record<string, unknown> | null }, ...keys: string[]) { for (const key of keys) { const value = row.detail_json?.[key]; if (value !== null && value !== undefined) return value } return null }
function detailList(row: { detail_json?: Record<string, unknown> | null }, key: string) { const value = row.detail_json?.[key]; return Array.isArray(value) ? value.join('、') : typeof value === 'string' ? value : '' }
function rowVisible(row: TableRow, values: unknown[]) { const text = JSON.stringify(row).toLowerCase(); if (keyword.value && !text.includes(keyword.value.toLowerCase())) return false; if (orgFilter.value && row.org_code !== orgFilter.value) return false; if (displayMode.value === 'difference') return values.some(isDifference); if (displayMode.value === 'missing') return values.some((value) => value === null || value === undefined || value === ''); return true }
const filteredSummaryRows = computed(() => summaryRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.difference_1,row.difference_2,row.taxable_income_difference,row.difference_4,row.difference_5,row.broker_occurrence_difference,row.other_income_difference]))); const filteredTaxRows = computed(() => taxAmountRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.current_difference,row.cumulative_difference,row.business_declared_difference]))); const filteredOccurrenceRows = computed(() => occurrenceRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.broker_occurrence_difference,row.declared_income_difference]))); const filteredDeclarationRows = computed(() => declarationRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.income_amount,row.tax_amount]))); const filteredSalaryTaxRows = computed(() => salaryTaxRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.difference]))); const filteredSalaryTaxableIncomeRows = computed(() => salaryTaxableIncomeRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.difference]))); const filteredBondInterestRows = computed(() => bondInterestRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.difference]))); const filteredRestrictedStockRows = computed(() => restrictedStockRows.value.filter((row) => rowVisible(row as unknown as TableRow,[row.difference]))); const filteredBankMatches = computed(() => bankMatchRows.value.filter((row) => (!selectedPaymentOrgCode.value || row.org_code === selectedPaymentOrgCode.value) && rowVisible(row as unknown as TableRow,[row.debit_amount])))
async function loadOverview() { if (props.periodId) overview.value = (await pitReconciliationApi.getOverview(props.periodId)).data }; async function loadReadiness() { if (props.periodId) readiness.value = (await pitReconciliationApi.getReadiness(props.periodId)).data }
async function ensureTabLoaded(tab: PitTabKey) { if (!props.periodId || tabLoaded[tab] || tabLoading[tab]) return; tabLoading[tab] = true; try { const periodId = props.periodId; if (tab === 'summary') summaryRows.value = (await pitReconciliationApi.getSummary(periodId)).data; if (tab === 'taxAmount') taxAmountRows.value = (await pitReconciliationApi.getTaxAmountChecks(periodId)).data; if (tab === 'occurrence') occurrenceRows.value = (await pitReconciliationApi.getOccurrenceChecks(periodId)).data; if (tab === 'declaration') declarationRows.value = (await pitReconciliationApi.getDeclarationSummary(periodId)).data; if (tab === 'salaryTax') salaryTaxRows.value = (await pitReconciliationApi.getDifferences(periodId,{ detail_type:'salary_tax' })).data; if (tab === 'salaryTaxableIncome') salaryTaxableIncomeRows.value = (await pitReconciliationApi.getDifferences(periodId,{ detail_type:'salary_taxable_income' })).data; if (tab === 'bondInterest') bondInterestRows.value = (await pitReconciliationApi.getDifferences(periodId,{ detail_type:'bond_interest_tax' })).data; if (tab === 'restrictedStock') restrictedStockRows.value = (await pitReconciliationApi.getDifferences(periodId,{ detail_type:'restricted_stock_tax' })).data; if (tab === 'payment') { if (!summaryRows.value.length) summaryRows.value = (await pitReconciliationApi.getSummary(periodId)).data; bankMatchRows.value = (await pitReconciliationApi.getBankMatches(periodId)).data }; tabLoaded[tab] = true } catch (error: any) { ElMessage.error(error?.response?.data?.detail || '核对数据加载失败') } finally { tabLoading[tab] = false } }
async function initializePage() { if (!props.periodId) return; pageLoading.value = true; try { await Promise.all([loadOverview(),loadReadiness()]); if (overview.value?.exists) await ensureTabLoaded(activeTab.value) } catch { ElMessage.error('个税底稿初始化失败') } finally { pageLoading.value = false } }; async function handleTabChange(value: string | number) { await ensureTabLoaded(value as PitTabKey) }
function resetPitPage() { overview.value = null; readiness.value = []; summaryRows.value = []; taxAmountRows.value = []; occurrenceRows.value = []; declarationRows.value = []; salaryTaxRows.value = []; salaryTaxableIncomeRows.value = []; bondInterestRows.value = []; restrictedStockRows.value = []; bankMatchRows.value = []; orgFilter.value = ''; keyword.value = ''; displayMode.value = 'all'; selectedPaymentOrgCode.value = null; (Object.keys(tabLoaded) as PitTabKey[]).forEach((key) => { tabLoaded[key] = false }) }
async function recalculate() { if (!props.periodId) return; recalculateLoading.value = true; try { await pitReconciliationApi.recalculate(props.periodId); resetPitPage(); await initializePage(); ElMessage.success('个税底稿已重新计算') } catch (error: any) { ElMessage.error(error?.response?.data?.detail || '计算失败') } finally { recalculateLoading.value = false } }
function openReasonEditor(row: TableRow, field: ReasonField, kind: ReasonKind) { editingReasonRow.value = row; editingReasonField.value = field; editingReasonKind.value = kind; editingReasonText.value = String(row[field] ?? ''); reasonDialogVisible.value = true }
async function saveReason() { const row = editingReasonRow.value; const field = editingReasonField.value; if (!row || !field) return; reasonSaving.value = true; try { const payload = { [field]: editingReasonText.value }; if (editingReasonKind.value === 'summary') await pitReconciliationApi.updateSummary(Number(row.id),payload as any); if (editingReasonKind.value === 'tax') await pitReconciliationApi.updateTaxAmountCheck(Number(row.id),payload as any); if (editingReasonKind.value === 'occurrence') await pitReconciliationApi.updateOccurrenceCheck(Number(row.id),payload as any); if (editingReasonKind.value === 'difference') await pitReconciliationApi.updateDifference(Number(row.id),{ manual_reason:editingReasonText.value }); row[field] = editingReasonText.value; reasonDialogVisible.value = false; ElMessage.success('人工原因已保存') } catch (error: any) { ElMessage.error(error?.response?.data?.detail || '保存失败') } finally { reasonSaving.value = false } }
async function drillDown(tab: PitTabKey, orgCode?: string) { orgFilter.value = orgCode || ''; activeTab.value = tab; await ensureTabLoaded(tab) }; function selectPaymentOrg(row: PitOrgSummary) { selectedPaymentOrgCode.value = row.org_code }; function openSalaryDrawer(row: unknown) { detailDrawerRow.value = row as PitDifferenceDetail; detailDrawerVisible.value = true }; function subjectDetailTab(row: PitTaxAmountCheck): PitTabKey { return row.subject_code === '21510008' ? 'bondInterest' : row.subject_code === '21510009' ? 'restrictedStock' : 'salaryTax' }
watch(() => props.periodId,async () => { resetPitPage(); await initializePage() },{ immediate:true })
const ReasonButton = defineComponent({ props:{ row:{ type:Object,required:true },field:{ type:String,required:true },kind:{ type:String,required:true } },setup(componentProps) { return () => h(ElButton,{ link:true,type:'primary',onClick:() => openReasonEditor(componentProps.row as TableRow,componentProps.field as ReasonField,componentProps.kind as ReasonKind) },() => String((componentProps.row as TableRow)[componentProps.field] ?? '填写原因')) } })
const MoneyColumn = defineComponent({ props:{ label:{ type:String,required:true },field:{ type:String,required:true } },setup(componentProps) { return () => h(ElTableColumn,{ label:componentProps.label,width:125,align:'right' },{ default:({ row }: { row:TableRow }) => formatMoney(row[componentProps.field]) }) } })
const DifferenceColumn = defineComponent({ props:{ label:{ type:String,required:true },field:{ type:String,required:true } },setup(componentProps) { return () => h(ElTableColumn,{ label:componentProps.label,width:125,align:'right' },{ default:({ row }: { row:TableRow }) => h('span',{ class:differenceClass(row[componentProps.field]) },formatMoney(row[componentProps.field])) }) } })
const SummaryDifferenceColumn = defineComponent({ props:{ label:{ type:String,required:true },field:{ type:String,required:true },tab:{ type:String,required:true } },setup(componentProps) { return () => h(ElTableColumn,{ label:componentProps.label,width:125,align:'right' },{ default:({ row }: { row:PitOrgSummary }) => h('button',{ class:['pit-diff-link',differenceClass((row as unknown as TableRow)[componentProps.field])],onClick:() => drillDown(componentProps.tab as PitTabKey,row.org_code) },formatMoney((row as unknown as TableRow)[componentProps.field])) }) } })
const TaxDifferenceColumn = defineComponent({ setup() { return () => h(ElTableColumn,{ label:'差异',width:125,align:'right' },{ default:({ row }: { row:PitTaxAmountCheck }) => h('button',{ class:['pit-diff-link',differenceClass(row.business_declared_difference)],onClick:() => drillDown(subjectDetailTab(row),row.org_code) },formatMoney(row.business_declared_difference)) }) } })
const ReasonColumn = defineComponent({ props:{ field:{ type:String,required:true },kind:{ type:String,required:true } },setup(componentProps) { return () => h(ElTableColumn,{ label:'人工原因',width:155 },{ default:({ row }: { row:TableRow }) => h(ReasonButton,{ row,field:componentProps.field,kind:componentProps.kind }) }) } })
const DetailMoneyColumn = defineComponent({ props:{ label:{ type:String,required:true },keys:{ type:Array,required:true },fallback:{ type:String,default:'' } },setup(componentProps) { return () => h(ElTableColumn,{ label:componentProps.label,width:125,align:'right' },{ default:({ row }: { row:PitDifferenceDetail }) => formatMoney(detailValue(row,...(componentProps.keys as string[])) ?? (componentProps.fallback ? (row as unknown as TableRow)[componentProps.fallback] : null)) }) } })
const DetailDifferenceColumn = defineComponent({ props:{ label:{ type:String,required:true } },setup(componentProps) { return () => h(ElTableColumn,{ label:componentProps.label,width:125,align:'right' },{ default:({ row }: { row:PitDifferenceDetail }) => h('span',{ class:differenceClass(row.difference) },formatMoney(row.difference)) }) } })
</script>

<style scoped>
.pit-page { display:grid; gap:16px; }.card-header { display:flex; align-items:flex-start; justify-content:space-between; gap:16px; }.card-header p { margin:6px 0 0; color:var(--el-text-color-secondary); font-size:13px; }.pit-toolbar,.pit-filter-bar { display:flex; align-items:center; justify-content:space-between; gap:12px; flex-wrap:wrap; }.pit-toolbar small { display:block; color:var(--el-text-color-secondary); margin-bottom:3px; }.pit-source-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(155px,1fr)); gap:10px; }.pit-source-card { display:grid; gap:5px; min-width:0; padding:11px; border:1px solid var(--el-border-color-lighter); border-radius:6px; }.source-name { font-weight:600; }.source-ref { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.source-ready,.source-ready_empty,.source-not_applicable { color:var(--el-color-success); }.source-missing,.source-invalid { color:var(--el-color-danger); }.source-issue { color:var(--el-color-warning); cursor:help; font-size:12px; }.pit-filter-org { width:180px; }.pit-filter-keyword { width:min(320px,100%); }.pit-table-wrap { overflow-x:auto; }.pit-reconciliation-table { min-width:1640px; }.pit-subtitle { margin:16px 0 8px; font-weight:600; }.pit-diff { font-variant-numeric:tabular-nums; }.pit-diff--difference { color:var(--el-color-danger); font-weight:600; }.pit-diff--missing { color:var(--el-text-color-secondary); }.pit-diff-link { border:0; background:transparent; padding:0; font:inherit; cursor:pointer; }.empty-inline { padding:16px 0; color:var(--el-text-color-secondary); } @media (max-width:720px) { .pit-filter-org,.pit-filter-keyword { width:100%; } }
</style>
